#!/bin/bash
grim -g "$(swaymsg -t get_tree | jq -r '.. | select(.focused?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"')" - | tee $HOME/Pictures/Screenshots/$(date +%s_grim.png) | wl-copy -t image/png

